Traceback (most recent call last):
  File "cbas/trainer.py", line 217, in <module>
    main(name=args_main.name,iteration=args_main.iteration,quantile=args_main.quantile)
  File "cbas/trainer.py", line 193, in main
    data = gather_scores(iteration, name)
  File "cbas/trainer.py", line 27, in gather_scores
    dfs = [pd.read_csv(csv_file) for csv_file in csv_files_list]
  File "cbas/trainer.py", line 27, in <listcomp>
    dfs = [pd.read_csv(csv_file) for csv_file in csv_files_list]
  File "/home/retienne/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/retienne/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/retienne/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/retienne/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/retienne/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
